// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

const databaseUrl = process.env.DATABASE_URL ?? env("DATABASE_URL");

export default defineConfig({
  schema: "./prisma/schema.prisma",

  datasource: {
    url: databaseUrl,
  },

  migrations: {
    path: "./prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
});
